# Local variables:
# coding: utf-8
# mode: sh
# End:

#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

if [ -f ~/.fbchef/environment ]; then
  source ~/.fbchef/environment
fi

FBCODE_DIR="$HOME"/fbsource/fbcode
FBCODE_PLATFORM=gcc-5-glibc-2.23
TP2="$FBCODE_DIR"/third-party-buck/"$FBCODE_PLATFORM"/build
