## -*- coding: utf-8;mode: sh; -*- ##

local master_file="/usr/facebook/ops/rc/master.zshrc"
if [ -f "$master_file" ]; then
  source "$master_file"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

EMACS_DIR=~/.dot-emacs
EMACS_SOCKET_NAME="sockettome.$HOST"
EMACS_SOCKET_FILE="/tmp/$EMACS_SOCKET_NAME"

export PATH=~/bin:~/.cask/bin:/opt/homebrew/bin:$PATH

alias g=git

assume () {
  eval $( ~/braid/scripts/assume_role $1 )
}

# if [ $( uname ) = "Darwin" ]; then
#     alias e="open -a /Applications/Emacs.app "
# else
#     alias e=_emacsfun
# fi

# ripgrep > silver searcher, but my fingers disagree
export RIPGREP_CONFIG_PATH=~/.ripgreprc
alias ag=rg

gff ()
{
    if [[ -z "$1" ]]; then
        echo "usage: gff <branch to fast-forward to HEAD>" > /dev/stderr;
        return 2;
    fi;
    git fetch . HEAD:“$1” && git checkout "$1"
}

gffm ()
{
    local ISH="${1:-HEAD}";
    shift;
    git fetch . "$ISH":$(git-main-branch) && git checkout $(git-main-branch)
}

export EMACS_DIR=~/.dot-emacs
export INPUTRC=~/.inputrc

EDITOR="emacs -nw"
# HGMERGE="emacsclient --socket-name=$EMACS_SOCKET_FILE --tty"

# Make the shell's builtin pwd default to -P
set -o physical

# Use bourne-shell-compatible word splitting.
setopt SH_WORD_SPLIT

# I don't particularly like the extended glob stuff...
unsetopt EXTENDED_GLOB

# Compatibility with bash's PROMPT_COMMAND
precmd() { eval "$PROMPT_COMMAND" }

export PNPM_HOME="/Users/jallen/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

alias pcl="pnpm run -w precommit-checklist"
autoload bashcompinit && bashcompinit
complete -C aws_completer aws
