# Local variables:
# coding: utf-8
# mode: sh
# End:

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# define LOCAL_ADMIN_SCRIPTS in /etc/zshenv
local master_file="${LOCAL_ADMIN_SCRIPTS}/master.zshrc"
if [ -f "$master_file" ]; then
  source "$master_file"
fi

export GOROOT=/usr/local/opt/go/libexec
export GOPATH=$HOME/go
export PATH=~/bin:$PATH:$GOPATH/bin:$GOROOT/bin

export EMACS_DIR=~/.dot-emacs
export INPUTRC=~/.inputrc

EDITOR="~/bin/e"
VISUAL=$EDITOR

alias g=git

local fb_prompt_file="${LOCAL_ADMIN_SCRIPTS}/scm-prompt"
if [ -f "$fb_prompt_file" ]; then
  source "$fb_prompt_file"
else
  echo "couldn't find FB SCM prompt file ${fb_prompt_file}"
fi
